# Generated by Django 2.0 on 2018-01-11 12:35

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
